#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "feedme"
name = "feedme"
description.en = "Turn any web page into a RSS feed."
description.fr = "Transformez n'importe quelle page web en un flux RSS."

version = "0.3.0~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "MIT"
demo = "https://createfeed.idroutebase.com"
admindoc = "https://github.com/ardi4s/feedme#documentation"
code = "https://github.com/ardi4s/feedme"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "150M"
ram.build = "0M"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    #Not supporting path install so far, cf. https://github.com/ardi4s/feedme/issues/1
    #[install.path]
    #type = "path"
    #default = "/feedme"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin_token]
    ask.en = "Admin token"
    ask.fr = "Jeton administrateur"
    help.en = "Will be asked to anyone willing to edit existing feeds' configuration."
    help.fr = "Sera demandé à quiconque souhaite éditer la configuration des flux existants."
    type = "string"
    redact = true

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/ardi4s/feedme/releases/download/v0.3.0/feedme_0.3.0_linux_amd64.tar.gz"
    amd64.sha256 = "93ce09114d771e3427a86883c7542b451b47cfaf9b82d077dcd777f78127251a"
    arm64.url = "https://github.com/ardi4s/feedme/releases/download/v0.3.0/feedme_0.3.0_linux_arm64.tar.gz"
    arm64.sha256 = "cca03400850f0f613ad64dff495ffb5c728c34a4c65009af8fa2003f8868a658"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "feedme_\\d+\\.\\d+\\.\\d+_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "feedme_\\d+\\.\\d+\\.\\d+_linux_arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/extract"
    api.show_tile = false 
    api.allowed = "visitors"
    api.auth_header = false
    api.protected = true

    [resources.ports]
    main.default = 8080
    browser.default = 3000

    [resources.apt]
    packages = ["chromium"]
