#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Initialize config variables made editable
if [[ $path != '/' ]]; then path_without_trailing_slash="$path"; else path_without_trailing_slash=""; fi
user_agent="feedme/0.1 (+https://$domain$path_without_trailing_slash/bot)"
respect_robots="true"
allow_private="false"
#admin_token="$admin_token"
ynh_app_setting_set --key=admin_token --value=$admin_token

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R $app:$app $install_dir
chmod +x "$install_dir/feedme"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.yaml" --destination="$data_dir/config.yaml"

chown -R $app:$app "$data_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service="${app}-browser" --template="feedme-browser.service"
ynh_config_add_systemd --service="${app}" --template="feedme.service"

yunohost service add "${app}-browser" --description="Headless browser instance for feedme" --log="/var/log/$app/${app}-browser.log"
yunohost service add "${app}" --description="Turn any web page into a RSS feed" --log="/var/log/$app/${app}.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

# Start systemd services
ynh_systemctl --service="${app}-browser" --action="start"
ynh_systemctl --service="${app}" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
